version: '3'
services:

  pgdb:
    environment:
    - DB_NAME=locketdb
    - PGDATA=/var/lib/postgresql/data/locketdb
    - POSTGRES_PASSWORD=123456
    image: 'postgres:12.3-alpine'
    ports:
    - 5432:5432
    restart: always
    volumes:
    - ./pgdb:/docker-entrypoint-initdb.d:ro
